wikimedia/restbase-mod-table-spec

- test/functional/simple.js
At one point (line 205) we were writing `into the past`, so static was not updated. Fixed test to check more common case when writes are happening sequentially in time.
Also SQLite doesn't support writing back in time yet. We could add this thin case back later, but I'm not sure it's a valuable test.
> Changed the order of the timestamps in tests

- test/functional/secondaryIndexes.js
Added a tests that verifies that secondary indexes work correctly when non-tic range keys are present in a main table (almost made such a mistake in sqlite module, and it was missed by existing tests)
> Added a test that non-tid range keys are handled correctly

- .travis.yml
- index.js
- lib/validator.js
- package.json
- test/functional/invalid_requests.js
- test/functional/varint.js
- test/lib/jshint.js
Added common validators for schema and request.
Request validation will be used only in SQLite, because cassandra will apply all proper restrictions itself.
The list of checks:
- Index should be non-empty array - so there must be at least one index
- Index cannot have duplicate attributes
- Index must have at least one 'hash' attribute
- All indexed attributes must exist in a schema
- Static indexes cannot be created on a table with no range indexes
- Only keys 'type', 'grace_ttl' and 'count' are allowed
- Type can be 'all' and 'latest'
- Schema must have at least one attribute
- Attribute types must be valid
- A projection must be a String or Array
- All projection attributes must exist in a table/index schema
- If primaryKeyOnly is true, every attribute in the predicate must be 'hash' …
> Validation

- .jshintignore
- lib/validator.js
- package.json
- test/functional/multi_ranged.js
- test/functional/revision_policies.js
- test/functional/secondaryIndexes.js
- test/functional/simple.js
- test/functional/types.js
- test/functional/varint.js
- test/lib/validator.js
This PR adds a tests and validation option for `interval` revision retention policy option.
An also used to implement this in both backends never removes the very first render of the revision, which is reflected in the tests.
Note that backend PRs depend on this one:
https://github.com/wikimedia/restbase-mod-table-sqlite/pull/15
https://github.com/wikimedia/restbase-mod-table-cassandra/pull/137
The bug: https://phabricator.wikimedia.org/T94524
> Interval revision policy test & validation

- package.json
- test/functional/simple.js
There was a bug in SQLite module when request domain wan't honoured in get request cache, so subsequent requests to the tables in different domains under up being made for the first domain.
> Added test for request domain bug in sqlite

- lib/validator.js
- test/functional/revision_policies.js
- test/functional/schema_migrations.js
For page -related information we would need to be able to add static columns to the schema. This PR adds this capability to Cassandra and SQLite.
> Tests for static column additions.

- package.json
- test/functional/schema_migrations.js
There was an idea to drop a `by_ns` secondary index, this adds a test for this feature in backends.
Bug: https://phabricator.wikimedia.org/T111959
> Added a test for secondaryIndex removal

- README.md
Move the table spec from RESTBase to the table spec module.
A more thorough update of the spec should follow in a separate PR.
> Update the README to include the table spec

- lib/validator.js
- package.json
- test/functional/invalid_requests.js
- test/lib/validator.js
When we try to insert a field that's not in the schema, cassandra silently ignores that and SQLite is throwing a non-descriptive error. However, extra fields clearly indicate a bug in the client - either on table schema, or on a query, so we need to fail-fast and throw an error.
After this is merged, SQLite module would be updated to require the news version of spec and anew version of sqlite will be released.
> Added a check for an extra column and tests

- package.json
- test/functional/revision_policies.js
In cassandra we start looking at a revisionRetentionPolicy starting from a row just after the row we've just inserted. This needs to be updated to support policy with count === 0, that just set a graceTTL.
SQLite module doesn't need updates, cassandra module is updated at https://github.com/wikimedia/restbase-mod-table-cassandra/pull/156
> Added a test that checks a revisionretentionPolicy with 0 revisions

- test/functional/invalid_requests.js
- test/functional/schema_migrations.js
- test/functional/secondaryIndexes.js
- test/functional/simple.js
In cassandra module, we don't run any table-cleanup-script after running tests, but rely on tests to delete the tables before the next run. Some tables were not deleted, which sometimes cause problems with test modification/rerun.
> Better cleanup test tables after tests

- README.md
- lib/validator.js
- package.json
- test/functional/revision_policies.js
After we've added support for `latest` revision policy with `count === 0`, a better name is needed for it. Here we use `temp`, but I'm happy to do some bike shedding on the naming. @wikimedia/services what are your thoughts?
> Rewrite ttl revision policy to latest with count = 0

- README.md
- lib/validator.js
- package.json
- test/functional/types.js
Adds spec changes and tests required to support `long` type in backends:
Corresponding PRs for backends:
Cassandra: https://github.com/wikimedia/restbase-mod-table-cassandra/pull/163
SQLite: https://github.com/wikimedia/restbase-mod-table-sqlite/pull/26
Bug: https://phabricator.wikimedia.org/T85576
> Spec & Tests: Support long type in storage backends

- README.md
- lib/validator.js
- package.json
- test/functional/simple.js
This PR adds support for setting a `_ttl` attribute on `PUT` queries, which represents a row TTL in seconds. Mixing `revisionRetentionPolicy` other than `all` with custom TTLs is not allowed, because it will break the policy contract.
The primary goal of this feature, it to make proper support for `preview` mode in public graphoid endpoints in RETBase (https://github.com/wikimedia/restbase/pull/388).
Corresponding backends changes:
SQLite: https://github.com/wikimedia/restbase-mod-table-sqlite/pull/27
Cassandra: https://github.com/wikimedia/restbase-mod-table-cassandra/pull/164
cc @wikimedia/services
> Spec & tests: Support custom _ttl attributes for individual rows

- package.json
> package.json: Use the valid SPDX name for the Apache v2 licence

- package.json
- test/functional/schema_migrations.js
https://github.com/wikimedia/restbase-mod-table-spec/pull/29 modified one of the schema migration tests, but it was not enough. Follow up is here.
> Tests: Make static column tests pass on travis

- README.md
- package.json
- test/functional/simple.js
To implement revision retention in the chunked bucket we need to be able to get and set TTLs for individual rows. This PR adds tests for this feature. However, the feature is dangerous, so I didn't update the documentation and didn't advertise it.
cc @wikimedia/services
> Tests: Added tests for setting and getting custom ttls to a row

- README.md
- lib/validator.js
- package.json
- test/functional/revision_policies.js
Tests and validation improvements for `latest_hash` policy. The idea is to implement a revision policy that would only keep the latest revision in the `key_rev_value` bucket. The policy implementation is quite generic - we will just remove all the older content where 'older' is defined by the order of the first `range` key in the table schema. 
Bug: https://phabricator.wikimedia.org/T128419
cc @wikimedia/services
> Tests for latest_hash rev policy

- package.json
- table.yaml
https://github.com/wikimedia/swagger-router/pull/51 changed the handling
of overlapping routes ending in a slash. As a result, we now need to
list the higher level route first, to avoid conflicts during tree
construction.
> Re-order overlapping table spec definitions; v0.1.11

- index.js
- package.json
This will break storage modules tests, but they are broken anyway right now because of npm not fetching the test directories for dependencies.
cc @wikimedia/services
> Make fetching the test utils on demand
